# Generated by Django 2.2.13 on 2022-08-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('expiration', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
