# Generated by Django 2.2.13 on 2022-08-29 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_date_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
