# Generated by Django 2.2.13 on 2022-09-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220829_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('beauty', 'Beauty'), ('health', 'Health'), ('auto', 'Auto'), ('food', 'Food'), ('other', 'Other')], default='beauty', max_length=5),
        ),
    ]
