# Generated by Django 2.2.13 on 2022-09-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220902_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('beauty', 'Beauty'), ('health', 'Health'), ('auto', 'Auto'), ('food', 'Food'), ('other', 'Other')], max_length=6),
        ),
    ]
