# Generated by Django 2.2.13 on 2022-09-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220902_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('beauty', 'Beauty'), ('health', 'Health'), ('auto', 'Auto'), ('food', 'Food'), ('other', 'Other')], max_length=6),
        ),
    ]
