# Generated by Django 2.2.13 on 2023-03-10 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230310_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_purchased',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
