# Generated by Django 2.2.13 on 2023-03-10 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230310_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_purchased',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
