# Generated by Django 2.2.13 on 2023-03-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230310_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_purchased',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration',
            field=models.DateField(blank=True),
        ),
    ]
